In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer

df = pd.read_csv('data/breast-cancer.csv',header=None)
df.columns = [
    "age",
    "menopause",
    "tumor-size",
    "inv-nodes",
    "node-caps",
    "deg-malig",
    "breast",
    "breast-quad",
    "irradiat",
    "Class"
]
# Drop Class column and NaN values
df = df.drop(columns=['Class'])
df = df.dropna()

X_train, X_test = train_test_split(df, test_size=0.2, random_state=43)

print(X_train.nunique())

age             6
menopause       3
tumor-size     11
inv-nodes       6
node-caps       2
deg-malig       3
breast          2
breast-quad     5
irradiat        2
dtype: int64


In [2]:

ohe_cols = ['node-caps', 'breast', 'breast-quad', 'irradiat']

ohe = OneHotEncoder(sparse_output=False)   # sklearn >= 1.2 uses sparse_output
ohe.fit(X_train[ohe_cols])
print(ohe.transform(X_test[ohe_cols])[:10])

print("\nFeature names:")
print(ohe.get_feature_names_out(ohe_cols))

[[1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]]

Feature names:
['node-caps_no' 'node-caps_yes' 'breast_left' 'breast_right'
 'breast-quad_central' 'breast-quad_left_low' 'breast-quad_left_up'
 'breast-quad_right_low' 'breast-quad_right_up' 'irradiat_no'
 'irradiat_yes']


In [3]:


ord_cols = ["menopause", "age", "tumor-size", "inv-nodes", "deg-malig"]

categories = [
    ['lt40', 'premeno', 'ge40'],    ['10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-89', '90-99'],
    ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34',
     '35-39', '40-44', '45-49', '50-54', '55-59'],
    ['0-2', '3-5', '6-8', '9-11', '12-14', '15-17', '18-20',
     '21-23', '24-26', '27-29', '30-32', '33-35', '36-39'],
    [1, 2, 3],
]

oe = OrdinalEncoder(categories=categories)
oe.fit(X_train[ord_cols])

print(oe.transform(X_test[ord_cols])[:10])


[[2. 5. 2. 0. 1.]
 [2. 5. 2. 0. 0.]
 [2. 5. 4. 5. 2.]
 [1. 4. 5. 1. 1.]
 [2. 5. 5. 0. 2.]
 [1. 2. 1. 0. 1.]
 [1. 2. 8. 0. 1.]
 [2. 5. 2. 0. 0.]
 [2. 5. 5. 0. 2.]
 [1. 2. 3. 0. 0.]]


In [4]:

ct = make_column_transformer(
    (OneHotEncoder(sparse_output=False), ohe_cols),
    (OrdinalEncoder(categories=categories), ord_cols),
)
ct.fit(X_train)
print(ct.transform(X_test)[:2])

[[1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 2. 5. 2. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 2. 5. 2. 0. 0.]]
